spring.application.name=ElectroMart
server.port=8081

# Basic Authentication (Development only)


# MongoDB Configuration
spring.data.mongodb.uri://mvshan02:wjFpEFSqyWTqXQl9@cluster0.cvpef.mongodb.net/
spring.data.mongodb.database=Electro_Mart_Product

# Debugging Logs for MongoDB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
